# @format

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector:
    app: second-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    # matchLabels:
    #   app: second-node
    #   tier: backend
    matchExpressions:
      - { key: app, operator: In, values: [second-node, first-node] }
  template:
    metadata:
      labels:
        app: second-node
        tier: backend
    spec:
      containers:
        - name: second-node
          image: nareshbhati/kube-first-app:2
