# @format

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector:
    app: second-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
