# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: nareshbhati/kube-user-api:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_ADRESSS
              value: auth-service.default
