# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  selector:
    matchLabels:
      app: story
  replicas: 2
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: nareshbhati/kube-story-app:2
          env:
            - name: FOLDER_NAME
              # value: story
              valueFrom:
                configMapKeyRef:
                  name: story-env
                  key: name_folder
          imagePullPolicy: Always
          volumeMounts:
            - name: story-volume
              mountPath: /app/story
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
