version: "3.8"
services:
  # mongodb:
  #   image: "mongo"
  #   volumes:
  #     - data:/data/db
  #   env_file:
  #     - ./env/mongodb.env
  backend:
    build: ./backend
    # volumes:
    #   - logs:/app/logs
    #   - ./backend:/app
    #   - /app/node_modules
    env_file:
      - ./env/backend.env
    ports:
      - "80:80"
    # depends_on:
    #   - mongodb
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
# volumes:
#   data:
#   logs:
